-- =============================================================================
--  One Sky — shared shooting-star tracker
--  Database schema for the `sightings` table
--
--  https://www.lucasliamlegacy.com/sky
--  Lucas & Liam Legacy Studios, St. Peter's, Cape Breton
--
--  Dumped from the live one-sky project on 2026-07-29 and tidied. This is the
--  authoritative description of the table: if the live database and this file
--  ever disagree, one of them is wrong and it is worth finding out which.
--
--  Rebuild from scratch with:
--      psql "$DATABASE_URL" -f schema.sql
--  or paste into the Supabase SQL editor. Every statement is written to be
--  safe to run twice.
--
--  SECURITY NOTE. The publishable (anon) key sits in public HTML by design.
--  Nothing in this file should ever be relaxed on the assumption that the key
--  is secret, because it is not. The policies and the trigger below ARE the
--  security model. Verified 2026-07-29: RLS on, insert rate-limited in
--  Postgres, no UPDATE or DELETE policy exists, so holders of the publishable
--  key cannot alter or remove a single row.
-- =============================================================================


-- -----------------------------------------------------------------------------
--  1. Table
-- -----------------------------------------------------------------------------
--  community is a SMALL INTEGER INDEX into the COMMUNITIES array in
--  sky/index.html, never free text. That is deliberate: there is no user-typed
--  string anywhere in this table, so there is nothing to escape and nothing to
--  inject. If you add a community to the page, add it to the END of that array
--  and widen the range check in the trigger below — inserting one in the middle
--  would silently relabel every sighting already recorded.
--
--  client_id is a random per-device string (crypto.randomUUID). Not a name, not
--  a location, not an account. It exists so the rate limit has something to
--  count against and so your own sighting does not fly at you twice.

create table if not exists public.sightings (
  id          bigint      generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  community   smallint,
  client_id   text        not null
);


-- -----------------------------------------------------------------------------
--  2. Indexes
-- -----------------------------------------------------------------------------
--  Two, and only two are needed.
--
--    created_at DESC              serves the 48-hour read policy and the feed
--    (client_id, created_at DESC) serves the per-device rate limit in the
--                                 trigger, which is the hot path on a shower
--                                 night — it runs on every single insert
--
--  The live database as dumped carried FOUR indexes: sightings_created_at_idx
--  and sightings_created_idx were byte-identical, as were
--  sightings_client_recent_idx and sightings_client_created_idx. Duplicates
--  cost write time on every insert and buy nothing. See the migration note at
--  the foot of this file for the two DROP statements that bring the live
--  database in line with this schema.

create index if not exists sightings_created_at_idx
  on public.sightings using btree (created_at desc);

create index if not exists sightings_client_recent_idx
  on public.sightings using btree (client_id, created_at desc);


-- -----------------------------------------------------------------------------
--  3. Row-level security
-- -----------------------------------------------------------------------------
--  Read: only the last 48 hours. Older rows are simply not reachable with the
--  publishable key, which keeps the exposure small without needing a cron job.
--  Write: allowed, but see the trigger — the real limits live there, because a
--  WITH CHECK clause cannot count rows.
--  There is NO update policy and NO delete policy. That absence is the point:
--  with RLS enabled, anything not explicitly permitted is refused.

alter table public.sightings enable row level security;

drop policy if exists "read recent sightings" on public.sightings;
create policy "read recent sightings"
  on public.sightings
  for select
  to anon, authenticated
  using (created_at > now() - interval '48 hours');

drop policy if exists "report a sighting" on public.sightings;
create policy "report a sighting"
  on public.sightings
  for insert
  to anon, authenticated
  with check (true);


-- -----------------------------------------------------------------------------
--  4. Rate limiting and validation
-- -----------------------------------------------------------------------------
--  The page has a 15-second cooldown on the button, but a client-side cooldown
--  is a courtesy, not a control — anyone can open the console and call the API
--  directly. These are the limits that actually hold, and they are one second
--  tighter than the client so ordinary users never bump into them by accident.
--
--  Three ceilings, each answering a different kind of abuse:
--    14 seconds per device   a person tapping fast
--    30 per device per hour  roughly double what an honest observer reports on
--                            the best night of the year; an all-night
--                            button-masher becomes background noise
--    400 per minute globally a script, or a very good night that has stopped
--                            being data and started being noise
--
--  SECURITY DEFINER with a pinned search_path: the function must read the table
--  to count, which the anon role's own policies would otherwise restrict, and
--  the pinned path stops search_path games.
--
--  new.created_at := now() is load-bearing. The server owns the clock. Without
--  it a client could post a sighting dated last Tuesday, or dated next year,
--  and walk straight past every window above.

create or replace function public.enforce_sighting_limits()
  returns trigger
  language plpgsql
  security definer
  set search_path to 'public'
as $function$
declare
  last_seen timestamptz;
  hourly    integer;
  burst     integer;
begin
  if new.client_id is null or length(new.client_id) < 8 or length(new.client_id) > 64 then
    raise exception 'bad_client';
  end if;

  -- Range matches the COMMUNITIES array in sky/index.html (10 entries, 0-9).
  if new.community is not null and (new.community < 0 or new.community > 9) then
    raise exception 'bad_community';
  end if;

  -- One indexed query gets both the cooldown check and the hourly count.
  -- Bounding to 1 hour is safe: a last sighting older than an hour can never
  -- trip a 14-second cooldown anyway.
  select max(created_at),
         count(*)
    into last_seen, hourly
    from public.sightings
   where client_id = new.client_id
     and created_at > now() - interval '1 hour';

  if last_seen is not null and last_seen > now() - interval '14 seconds' then
    raise exception 'rate_limited';
  end if;

  if hourly >= 30 then
    raise exception 'hourly_limited';
  end if;

  select count(*) into burst
    from public.sightings
   where created_at > now() - interval '1 minute';

  if burst >= 400 then
    raise exception 'global_rate_limited';
  end if;

  new.created_at := now();   -- the server owns the clock, not the browser
  return new;
end;
$function$;

drop trigger if exists sightings_limits on public.sightings;
create trigger sightings_limits
  before insert on public.sightings
  for each row
  execute function public.enforce_sighting_limits();


-- -----------------------------------------------------------------------------
--  5. Realtime
-- -----------------------------------------------------------------------------
--  This is what makes it a shared sky rather than a feed. A sighting reported
--  in Glace Bay reaches a phone in L'Ardoise in about a second. The page also
--  polls every 45 seconds as a fallback, because websockets drop every time a
--  phone screen sleeps — but the socket is the thing that makes it feel live.
--
--  Wrapped because re-adding a table already in the publication is an error.

do $$
begin
  alter publication supabase_realtime add table public.sightings;
exception
  when duplicate_object then null;
  when undefined_object then
    raise notice 'publication supabase_realtime not found — enable Realtime for this table in the Supabase dashboard';
end;
$$;


-- =============================================================================
--  MIGRATION NOTE — 2026-07-29
--
--  The live database carries two pairs of duplicate indexes. They are harmless
--  but not free: every insert maintains all four, and inserts are the hot path
--  on the one night of the year this page is busy. Safe to drop; run these
--  against the live database to match this schema. CONCURRENTLY so nothing
--  blocks while people are watching.
--
--      drop index concurrently if exists public.sightings_created_idx;
--      drop index concurrently if exists public.sightings_client_created_idx;
--
--  Confirm afterwards:
--
--      select indexname from pg_indexes
--       where schemaname = 'public' and tablename = 'sightings';
--
--  Expect three: sightings_pkey, sightings_created_at_idx,
--  sightings_client_recent_idx.
-- =============================================================================
